# docker-build:
# 	docker build -t guanw0826/kubernetes-websocket-client .

# docker-push:
# 	docker push guanw0826/kubernetes-websocket-client

# docker-run:
# 	docker run -d guanw0826/kubernetes-websocket-client