docker-build:
	docker build -t guanw0826/kubernetes-websocket-server .

docker-push:
	docker push guanw0826/kubernetes-websocket-server

docker-run:
	docker run -d -p 8890:8890 guanw0826/kubernetes-websocket-server